server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/detroitauctionshippers
    username: admin    
    password: admin
  jpa :
    hibernate:
      ddl-auto: create
      
  mail:
    properties:
      mail:
        smtp:
          socketFactory:
            port: '587'
            class: javax.net.ssl.SSLSocketFactory
            fallback: 'true'
          auth: 'true'
          starttls : 
            enable : 'true'
    host: smtp.office365.com
    username: arenelliyadagiri@outlook.com
    password: Lkjhg@9989
